import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=''>
      <main className=" flex-col items-center bg-gradient-to-r from-blue-300 to-slate-50 ">
        <Header/>
        
        {children}
        <section className="w-[100%] bg-[#003366]  py-16 ">
      <Footer/>
     </section>
        </main>
        </body>
    </html>
  );
}
